FROM golang as builder
ARG SOURCE_LOCATION=/
WORKDIR ${SOURCE_LOCATION}
RUN go get -d -v github.com/gorilla/mux \
	&& go get -d -v gopkg.in/mgo.v2/bson \
	&& go get -d -v gopkg.in/mgo.v2 \
	&& go get -d -v github.com/confluentinc/confluent-kafka-go/kafka \
	&& go get -d -v github.com/prometheus/client_golang/prometheus/promhttp
COPY main.go .
RUN CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -a -installsuffix cgo -o app .

FROM ubuntu:19.10  
ARG SOURCE_LOCATION=/
#RUN apk --no-cache add curl
EXPOSE 9090
WORKDIR /root/
COPY --from=builder ${SOURCE_LOCATION} .
CMD ["./app"]
